### ISSUE TITLE
DateTimeParseException on cockpit data

### ISSUE THREAD

**Issue by robertaramar** [robertaramar/MyZOE#3]
Reported for retrieving with API V2 on a Ph1 vehicle.

java.time.format.DateTimeParseException: Text '2020-05-26T08:05:46+02:00' could not be parsed at index 19
 at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1949)
 at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
 at java.time.Instant.parse(Instant.java:389)
 at de.aramar.zoe.utilities.Tools.getLocalizedTimestamp(Tools.java:77)
 at de.aramar.zoe.ui.home.HomeFragment.updateData(HomeFragment.java:291)
 at de.aramar.zoe.ui.home.HomeFragment.lambda$onActivityCreated$0$HomeFragment(HomeFragment.java:108)
 at de.aramar.zoe.ui.home.-$$Lambda$HomeFragment$9IMCHaTlcbMGO7ooQ3Fs0083noA.onChanged(Unknown Source:4)
 at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
 at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
 at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
 at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
 at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
 at android.os.Handler.handleCallback(Unknown Source:2)
 at android.os.Handler.dispatchMessage(Unknown Source:4)
 at android.os.Looper.loop(Unknown Source:242)
 at android.app.ActivityThread.main(Unknown Source:98)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
 at com.android.internal.os.ZygoteInit.main(Unknown Source:275)

**Comment by robertaramar** [comment]
fixed with 0.1.6
